version: '3'
services:
  client:
    image: 'gurpreet1993/multi-client'
    mem_limit: 256m
    hostname: client
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - WDS_SOCKET_PORT=0
  server:
    image: 'gurpreet1993/multi-server'
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
      - PGSSLMODE=${PGSSLMODE:-require}
  worker:
    image: 'gurpreet1993/multi-worker'
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: 'gurpreet1993/multi-nginx'
    mem_limit: 128m
    hostname: nginx
    ports:
      - '80:80'
