services:
  client:
    image: "gs8368/multi-client:latest"
    mem_limit: 128m
    hostname: client

  server:
    image: "gs8368/multi-server:latest"
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - PGUSER=${PGUSER:-postgres}
      - PGHOST=${PGHOST:-postgres}
      - PGDATABASE=${PGDATABASE:-fibvalues}
      - PGPASSWORD=${PGPASSWORD:-postgrespassword}
      - PGPORT=${PGPORT:-5432}

  worker:
    image: "gs8368/multi-worker:latest"
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}

  nginx:
    image: "gs8368/multi-nginx:latest"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"
